<?php

namespace BatiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AffecterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffecterRepository extends EntityRepository
{
}
