<?php

namespace BatiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArtisanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtisanRepository extends EntityRepository
{
    
    public function supprimerArtisan($idArtisan){
        $query = $this->_em->createQuery('delete from BatiBundle:Artisan a where a.idartisan =:idArtisan')
                ->setParameter('idArtisan', $idArtisan);
        
        $result = $query->execute();
        return $result;
    }
    
    
}
