<?php

namespace BatiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CongeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CongeRepository extends EntityRepository
{
}
