<?php

namespace BatiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntrepreneurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepreneurRepository extends EntityRepository
{
}
